local_costmap: 
  global_frame: map #odom #map
  robot_base_frame: base_link 
  update_frequency: 5.0 
  publish_frequency: 10.0 
  static_map: false 
  rolling_window: true 
  width: 30.0 
  height: 30.0 
  resolution: 0.05 # The resolution of map is meters per cell.
#  plugins:
#   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
#    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
#    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}